### ISSUE TITLE
AngularJS and ng-model

### ISSUE THREAD

**Issue by wehowski** [dwiyatci/jquery-inputsearch#4] opened 2016-03-23 11:32 UTC
Hi, 
first thanks for this, great job.

I use AngularJS, if I set the ng-model Attribute to an input element, the scope variable in the view does not update when changing input.

regards,
Till

**Comment by dwiyatci** [comment] 2016-03-25 22:30
Hey, thanks! Care to share bits of code snippet of yours so that I can better look into the issue?

**Comment by wehowski** [comment] 2016-03-25 23:05
Hello,
`<input type="text" ng-model="packagename" placeholder="vendor/package" data-clear-btn="true" />`

`$('*[data-clear-btn="true"]').inputSearch({ searchIconVisible: false});`

`<span ng-bind="packagename"></span>`

If I onchange the input element angularJS should update corresponding innerHTML of the span.
This is working if I remove the data-clear-btn="true" element from input, but if I use the inputSearch plugin on the input element angular does not its job.
Maybe there is a better solution than the plugin for angularjs, but I find it good and handy although.

**Comment by dwiyatci** [comment] 2016-03-27 21:54
I couldn't seem to reproduce your issue. Please have a look into [the fiddle that I just made](https://jsfiddle.net/glenn/2ca4t53f/) - maybe it could shed you some light. I suppose there's something wrong with how you setup your AngularJS code :innocent:

**Comment by wehowski** [comment] 2016-03-28 01:34
Thank you! 
I do not use
`<div id="app">`
but something like this: https://github.com/luisperezphd/ngModule/blob/master/angular.ng-modules.js
Ok, so angular is working with your plugin, I will let you know if I found the problem in my code...

**Comment by dwiyatci** [comment] 2016-03-31 12:41
@wehowski Ok, great. I guess I will close this issue for now since the problem does not lie within my plugin (it could be reopened later if it needs to). Also, a star to this repo would be appreciated. Cheers! :)

**Closed as completed by dwiyatci** 2016-03-31 12:41 UTC
